### ISSUE TITLE
Behind a reverse proxy, long posts produce a HTTP 414 error on the proxy and are not posted

### ISSUE THREAD

**Issue by scotthansonde** [scripting/1999-project#16]
##### Description of the problem

On the 1999-server mailing list, Phil Ulrich wrote at https://groups.google.com/forum/#!topic/1999-server/ScQ9y7EA2SA:

> Behind the scenes, 1999 seems to be using some URLs with very long GET parameters to work its magic - namely posting and editing. I discovered inadvertently this morning that if you are proxying 1999 behind Apache (Apache 2, at least), if you write a post in excess of ~5000-6000 characters, Apache will reject the post with a HTTP 414 error.
> 
> Also, if you edit a post to be in excess of this length, Apache will reject it in the same fashion, and the edited post will be completely blank.
> 
> I guess what I'm saying is: unless you're willing to compile Apache with a larger DEFAULT_LIMIT_REQUEST_LINE constant, either don't proxy 1999 behind Apache, or don't write overly wordy posts like me. :)
##### Steps to reproduce
1. Installed a fresh VPS, installed nodeStorage and set up apache2 (or nginx) as a proxy from port 80 to port 1999
2. Pasted 3000 words from a lorem ipsum generator into a post.
3. The post is saved with no text with an error in the log file of the proxy:
   31.17.***.*** - - [28/Apr/2016:11:28:38 -0400] "POST /editchatmessage?oauth_token=*******&oauth_token_secret=*******&chatLog=papascott&flNotWhitelisted=false&text=%3Cp%3EHelp!%26nbsp%3B%3Cspan%3ELorem%20ipsum%20dolor%20sit%20amet%2C%20assentior%20disputando%20mei%20ut%2C%20te%20legere%20lucilius%20sed.%20Ei%20cum%20fabulas%20accusam%20moderatius%2C%20labore%20voluptatum%20sed%20eu.%20Mel%20no%20eirmod%20iuvaret%20recteque%2C%20id%20est%20malis%20utamur%20delenit%2C%20id%20pri%20populo%20vidisse.%20Qui%20an%20persequeris%20reformidans%2C%20mei%20cu%20porro%20delenit%20honestatis.%20Nullam%20alterum%20recteque%20usu%20cu%2C%20an%20semper%20bonorum%20facilisis%20eam.%20Altera%20luptatum%2... goes on and on ends with endis%20accommodare.%20Iu" 414 201 "-" "-"

Using the app without a proxy the long post works perfectly
##### What you expected to happen

Having read Phil's post, I knew it was going to bomb out. :-)

Seriously, I expected my opus to be saved in its entirety.
##### Other data

Chrome on OSX, server on Digital Ocean with Ubuntu

**Comment by scripting** [comment]
Thanks for filling out the new template. In the future, you can just use it as a checklist, it's not for you Scott, it's for the people who make me ask the questions manually. I've seen this technique used in other projects and it gets things done more quickly with less teeth-pulling.

Anyway -- I found the problem right away. I did a half-assed job of implementing this. Now it's going to be tricky to turn this corner, but it's a good thing to do, because it's developing some new practices that make this kind of thing easier to deal with in the future.

I'll have a new server release later today that has this fixed, and at the same time a new client that uses the new feature on the server AND works with servers that haven't yet installed the new software. 

I'll post a note on the mail list when this happens. So I'm closing this issue for now. Thanks again for the great report! :-)

**Comment by scripting** [comment]
There a new client and server release with this fixed.

http://my.1999.io/users/1999io/2016/04/28/0017.html

Dave

**Comment by scotthansonde** [comment]
I fired up the test server, made sure nodeStorage had updated, and now the ultra-long post works perfectly.

I thought about overwriting the template since I know how to write a bug report, but I decided instead to be a good citizen and set a good example. But now I wish I had used a movie quote for what I expected... :-)

##### What you expected to happen

James Bond: Do you expect me to talk?
Auric Goldfinger: No, Mr. Bond, I expect you to die!
