### ISSUE TITLE
Inserting inline images deletes posts

### ISSUE THREAD

**Issue by stoppableforce** [scripting/1999-project#7]
1999 version: 0.88i. Browser version, since it might be relevant in this case: Google Chrome for Linux, Version 48.0.2564.103 (64-bit).

This is actually two issues, but I'm pretty sure they're related.

**Steps to reproduce (1):**
1. Write a new post in 1999. Doesn't matter how long or short.
2. Drag and drop an image into the post somewhere.
3. Click Post.

**What I expected:** A new post with an image in it.
**What actually happened:** The post was deleted from the editor, and no new post was actually made.

**Steps to reproduce (2):**
1. Edit an existing post in 1999. (Does not matter if you are editing it on the story page or in the editor, I have experienced this behavior in both places.)
2. Drag and drop an image into the post somewhere.
3. Click Update.

**What I expected:** Editing to end, and the post to be updated with an image in it.
**What actually happened:** Editing did not end, but the entire pre-existing post - image, text, and all - is deleted from the editor.

**Comment by scripting** [comment]
Since the docs aren't complete yet, it's hard to tell, but images are not in any way a supported feature.

I'm using medium-editor, and have a plan for how to support arbitrary HTML, but I haven't found the time to dive into the medium-editor code to make it happen. Actually hoping someone gets to it before I do.

I posted the plan on the issues site for medium-editor.

https://github.com/yabwe/medium-editor/issues/1048
